# Generated by Django 4.0.1 on 2022-03-21 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(default='None Selected')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TG', 'Transgender'), ('NB', 'Non-binary'), ('Other', 'Other'), ('None Selected', 'None Selected')], default='None Selected', max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='None Selected', max_length=256)),
                ('partner_preferences', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TG', 'Transgender'), ('NB', 'Non-binary'), ('Other', 'Other'), ('None Selected', 'None Selected')], default='None Selected', max_length=256)),
                ('hobbies_interests', models.CharField(max_length=3000)),
                ('zodiac', models.CharField(choices=[('Sag', 'Sagittarius'), ('Ari', 'Aries'), ('Tau', 'Taurus'), ('Gem', 'Gemini'), ('Can', 'Cancer'), ('Leo', 'Leo'), ('Vir', 'Virgo'), ('Lib', 'Libra'), ('Sco', 'Scorpio'), ('Cap', 'Capricorn'), ('Aqu', 'Aquarius'), ('Pis', 'Pisces'), ('None Selected', 'None Selected')], default='None Selected', max_length=256)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
